Repository istio/bots, pull requests merged in 2019-07, with the labels that each got.

#51 add support for pointer types in Spanner layer
  policybot/pkg/storage/spanner/convert.go
  policybot/pkg/storage/spanner/convert_test.go
  policybot/pkg/storage/spanner/query.go
  policybot/pkg/storage/spanner/read.go
  policybot/pkg/storage/spanner/update.go
  policybot/pkg/storage/spanner/write.go
  policybot/pkg/storage/types.go
Labels: size/XL

#52 support case insensitivity for Spanner column names
  policybot/pkg/storage/spanner/convert.go
  policybot/pkg/storage/spanner/convert_test.go
Labels: size/M

#53 Policy Bot improvements.
  go.mod
  go.sum
  policybot/cmd/syncer.go
  policybot/dashboard/dashboard.go
  policybot/dashboard/renderContext.go
  policybot/dashboard/sass/_all.scss
  policybot/dashboard/sass/widgets/_user-gallery.scss
  policybot/dashboard/sass/widgets/_user-page.scss
  policybot/dashboard/static/js/fitty.min.js
  policybot/dashboard/templates/layout/assets.gen.go
  policybot/dashboard/templates/layout/base.html
  policybot/dashboard/templates/layout/primary.html
  policybot/dashboard/templates/widgets/assets.gen.go
  policybot/dashboard/templates/widgets/header.html
  policybot/dashboard/topics/commithub/topic.go
  policybot/dashboard/topics/coverage/topic.go
  policybot/dashboard/topics/features/topic.go
  policybot/dashboard/topics/flakes/topic.go
  policybot/dashboard/topics/home/topic.go
  policybot/dashboard/topics/issues/topic.go
  policybot/dashboard/topics/maintainers/all.html
  policybot/dashboard/topics/maintainers/assets.gen.go
  policybot/dashboard/topics/maintainers/control.html
  policybot/dashboard/topics/maintainers/list.html
  policybot/dashboard/topics/maintainers/single.html
  policybot/dashboard/topics/maintainers/topic.go
  policybot/dashboard/topics/maintainers/user.html
  policybot/dashboard/topics/members/topic.go
  policybot/dashboard/topics/perf/topic.go
  policybot/dashboard/topics/pullrequests/topic.go
  policybot/dashboard/ts/core/utils.ts
  policybot/deploy/kube/templates/cron-syncer-events.yaml
  policybot/handlers/githubwebhook/filters/refresher/refresher.go
  policybot/handlers/githubwebhook/filters/resultgatherer/resultgatherer.go
  policybot/pkg/config/args.go
  policybot/pkg/storage/spanner/query.go
  policybot/pkg/storage/store.go
  policybot/pkg/storage/types.go
  policybot/pkg/syncer/fetch.go
  policybot/pkg/syncer/syncer.go
  policybot/policybot.yaml
Labels: size/XXL

#56 Revamp UI composition
  policybot/cmd/server.go
  policybot/dashboard/dashboard.go
  policybot/dashboard/notFound.go
  policybot/dashboard/oauth.go
  policybot/dashboard/renderContext.go
  policybot/dashboard/sidebarEntry.go
  policybot/dashboard/templates/widgets/assets.gen.go
  policybot/dashboard/templates/widgets/sidebar.html
  policybot/dashboard/templates/widgets/sidebar_level.html
  policybot/dashboard/topics/commithub/topic.go
  policybot/dashboard/topics/coverage/topic.go
  policybot/dashboard/topics/features/topic.go
  policybot/dashboard/topics/flakes/topic.go
  policybot/dashboard/topics/home/assets.gen.go
  policybot/dashboard/topics/home/page.html
  policybot/dashboard/topics/home/topic.go
  policybot/dashboard/topics/issues/topic.go
  policybot/dashboard/topics/maintainers/assets.gen.go
  policybot/dashboard/topics/maintainers/filteredTopic.go
  policybot/dashboard/topics/maintainers/list.html
  policybot/dashboard/topics/maintainers/topic.go
  policybot/dashboard/topics/maintainers/user.html
  policybot/dashboard/topics/members/topic.go
  policybot/dashboard/topics/perf/topic.go
  policybot/dashboard/topics/pullrequests/topic.go
  policybot/dashboard/types/render.go
  policybot/pkg/config/args.go
  policybot/policybot.yaml
Labels: cla: yes, size/XXL

#57 update pull request table schema
  policybot/pkg/gh/convert.go
  policybot/pkg/storage/types.go
  policybot/pkg/syncer/syncer.go
  policybot/spanner.ddl
Labels: cla: yes, size/S

#58 PolicyBot improvements
  policybot/dashboard/topics/maintainers/assets.gen.go
  policybot/dashboard/topics/maintainers/list.html
  policybot/dashboard/topics/maintainers/topic.go
  policybot/pkg/storage/spanner/query.go
Labels: cla: yes, size/M

#54 abstract resultgatherer use of GCS into blobstorage
  policybot/cmd/server.go
  policybot/handlers/githubwebhook/filters/resultgatherer/resultgatherer.go
  policybot/pkg/blobstorage/gcs/store.go
  policybot/pkg/blobstorage/store.go
  policybot/pkg/resultgatherer/resultgatherer.go
  policybot/pkg/resultgatherer/resultgatherer_test.go
Labels: cla: yes, size/L

#60 add a warning before pushing
  policybot/Makefile
Labels: cla: yes, size/XS

#49 Allow testresults to be synced.
  go.mod
  policybot/cmd/syncer.go
  policybot/handlers/githubwebhook/filters/testresultfilter/testresultfilter.go
  policybot/pkg/config/args.go
  policybot/pkg/resultgatherer/resultgatherer.go
  policybot/pkg/resultgatherer/resultgatherer_test.go
  policybot/pkg/storage/spanner/convert.go
  policybot/pkg/storage/types.go
  policybot/pkg/syncer/syncer.go
  policybot/policybot.yaml
Labels: cla: yes, size/XL

#62 set HeadCommit and BranchName in PullRequests to NOT NULL
  policybot/pkg/gh/convert.go
  policybot/pkg/storage/types.go
  policybot/pkg/syncer/syncer.go
Labels: cla: yes, size/S

#61 PolicyBot improvements
  policybot/Makefile
  policybot/cmd/server.go
  policybot/cmd/syncer.go
  policybot/handlers/githubwebhook/filters/labeler/labeler.go
  policybot/handlers/githubwebhook/filters/nagger/nagger.go
  policybot/handlers/githubwebhook/filters/unstaler/unstaler.go
  policybot/pkg/config/args.go
  policybot/pkg/gh/comments.go
  policybot/pkg/storage/spanner/query.go
  policybot/policybot.yaml
Labels: cla: yes, size/L

#63 add list of artifact paths to TestResults
  policybot/pkg/blobstorage/gcs/store.go
  policybot/pkg/blobstorage/store.go
  policybot/pkg/resultgatherer/resultgatherer.go
  policybot/pkg/storage/types.go
  policybot/spanner.ddl
Labels: cla: yes, size/M

#64 This will sync test results regularly.
  policybot/deploy/kube/templates/cron-syncer-testresults.yaml
Labels: cla: yes, size/S
