Repository istio/bots, pull requests merged in 2019-10, with the labels that each got.

#83 add coverage config
  go.mod
  policybot/pkg/coverage/config.go
  policybot/pkg/coverage/config_test.go
Labels: cla: yes, size/L

#84 add coverage data storage query helper
  policybot/pkg/storage/spanner/query.go
  policybot/pkg/storage/store.go
Labels: cla: yes, size/M

#85 implement coverage gates and reporting
  policybot/handlers/githubwebhook/filters/testresultfilter/testresultfilter.go
  policybot/pkg/coverage/config.go
  policybot/pkg/coverage/config_test.go
  policybot/pkg/coverage/coverage.go
  policybot/pkg/coverage/diff.go
  policybot/pkg/coverage/diff_test.go
Labels: cla: yes, size/L

#86 Update common files.
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
Labels: cla: yes, size/M

#87 Add support for tracking user's company affiliation.
  Makefile
  common/.commonfiles.sha
  policybot/cmd/root.go
  policybot/cmd/userdata.go
  policybot/pkg/storage/spanner/schema.go
  policybot/pkg/storage/spanner/write.go
  policybot/pkg/storage/store.go
  policybot/pkg/storage/types.go
  policybot/pkg/userdata/userdata.go
  policybot/spanner.ddl
  policybot/userdata.yaml
Labels: cla: yes, size/L

#88 Bunch of bot improvements
  policybot/Makefile
  policybot/cmd/server.go
  policybot/dashboard/dashboard.go
  policybot/handlers/githubwebhook/filters/boilerplatecleaner/cleaner.go
  policybot/handlers/githubwebhook/filters/refresher/refresher.go
  policybot/pkg/config/args.go
  policybot/pkg/gh/convert.go
  policybot/pkg/storage/spanner/query.go
  policybot/pkg/storage/store.go
  policybot/pkg/storage/types.go
  policybot/pkg/syncer/syncer.go
  policybot/pkg/userdata/userdata.go
  policybot/policybot.yaml
  policybot/spanner.ddl
  policybot/userdata.yaml
Labels: cla: yes, size/XXL

#89 Cleanup boilerplate cleaner.
  policybot/handlers/githubwebhook/filters/boilerplatecleaner/cleaner.go
Labels: cla: yes, size/S

#90 Improve boilerplate cleaner.
  policybot/handlers/githubwebhook/filters/boilerplatecleaner/cleaner.go
  policybot/policybot.yaml
Labels: cla: yes, size/S
