Repository istio/bots, pull requests merged in 2019-08, with the labels that each got.

#66 fix testresult syncer cron
  policybot/deploy/kube/templates/cron-syncer-testresults.yaml
  policybot/pkg/syncer/syncer.go
  policybot/pkg/syncer/syncer_test.go
Labels: cla: yes, size/M

#65 Adding info about issues to the issues tab
  policybot/dashboard/dashboard.go
  policybot/dashboard/topics/issues/assets.gen.go
  policybot/dashboard/topics/issues/list.html
  policybot/dashboard/topics/issues/page.html
  policybot/dashboard/topics/issues/summary.html
  policybot/dashboard/topics/issues/topic.go
  policybot/pkg/storage/spanner/query.go
  policybot/pkg/storage/store.go
Labels: cla: yes, size/L

#68 use correct event type for test result filter
  policybot/handlers/githubwebhook/filters/testresultfilter/testresultfilter.go
Labels: cla: yes, size/M

#69 Fix auto label config block.
  README.md
  policybot/handlers/githubwebhook/filters/labeler/labeler.go
  policybot/policybot.yaml
Labels: cla: yes, size/S

#71 Fix linting from CI system.
  Makefile
  policybot/cmd/server.go
  policybot/pkg/syncer/syncer_test.go
Labels: cla: yes, size/S

#70 Fix broken test after addition of artifacts
  policybot/pkg/resultgatherer/resultgatherer_test.go
Labels: cla: yes, size/XS

#76 Spruce up.
  .commonfiles.sha
  Makefile
  Makefile.common.mk
  Makefile.core.mk
  policybot/Dockerfile
  policybot/Makefile
  policybot/scripts/gen_dashboard.sh
  policybot/scripts/gen_topic.sh
  scripts/lint_copyright_banner.sh
Labels: cla: yes, size/M

#77 Update common files.
  .commonfiles.sha
  Makefile
  Makefile.common.mk
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/report_build_info.sh
  scripts/check_dockerfiles.sh
  scripts/lint_copyright_banner.sh
  scripts/run_gobindata.sh
  scripts/run_gofmt.sh
Labels: cla: yes, size/L

#78 Added the ability to automatically create & update milestones across repos
  Makefile
  Makefile.core.mk
  README.md
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/mdl.rb
  common/config/sass-lint.yml
  common/config/tslint.json
  go.mod
  policybot/.gitignore
  policybot/Makefile
  policybot/README.md
  policybot/cmd/milestonemaker.go
  policybot/cmd/root.go
  policybot/dashboard/sass/widgets/_control.scss
  policybot/dashboard/sass/widgets/_user-gallery.scss
  policybot/dashboard/sass/widgets/_user-page.scss
  policybot/dashboard/ts/core/authenticator.ts
  policybot/dashboard/ts/core/utils.ts
  policybot/deploy/policybot/Chart.yaml
  policybot/deploy/policybot/templates/cron-flakechaser.yaml
  policybot/deploy/policybot/templates/cron-syncer-events.yaml
  policybot/deploy/policybot/templates/cron-syncer-issues.yaml
  policybot/deploy/policybot/templates/cron-syncer-misc.yaml
  policybot/deploy/policybot/templates/cron-syncer-prs.yaml
  policybot/deploy/policybot/templates/cron-syncer-testresults.yaml
  policybot/deploy/policybot/templates/cron-syncer-zenhub.yaml
  policybot/deploy/policybot/templates/deployment.yaml
  policybot/deploy/policybot/templates/ingress.yaml
  policybot/deploy/policybot/templates/secret.yaml
  policybot/deploy/policybot/templates/service.yaml
  policybot/deploy/policybot/values.yaml
  policybot/pkg/config/args.go
  policybot/pkg/flakechaser/README.md
  policybot/pkg/labelmaker/labelmaker.go
  policybot/pkg/milestonemaker/milestonemaker.go
  policybot/policybot.yaml
  policybot/scripts/lint_dashboard.sh
Labels: cla: yes, size/L
