Repository istio/bots, pull requests merged in 2019-12, with the labels that each got.

#110 comment out coverage hooks to fix other repos
  policybot/handlers/githubwebhook/refresher/refresher.go
Labels: cla: yes, size/M

#111 Introduce the Welcomer handler.
  policybot/cmd/server.go
  policybot/config/milestones/1.4.yaml
  policybot/config/milestones/1.6.yaml
  policybot/config/users.yaml
  policybot/config/welcome/istio.io.yaml
  policybot/handlers/githubwebhook/lifecycler/lifecycler.go
  policybot/handlers/githubwebhook/welcomer/record.go
  policybot/handlers/githubwebhook/welcomer/welcomer.go
  policybot/pkg/storage/spanner/query.go
  policybot/pkg/storage/store.go
Labels: cla: yes, size/L

#113 Fix regex for area selection
  policybot/config/boilerplates/area-selection.yaml
Labels: cla: yes, size/S

#95 Increase speed of syncer for testresults
  go.mod
  go.sum
  licenses/github.com/eapache/channels/LICENSE
  licenses/gotest.tools/LICENSE
  licenses/gotest.tools/internal/difflib/LICENSE
  policybot/dashboard/templates/layout/assets.gen.go
  policybot/dashboard/templates/widgets/assets.gen.go
  policybot/dashboard/topics/commithub/assets.gen.go
  policybot/dashboard/topics/coverage/assets.gen.go
  policybot/dashboard/topics/features/assets.gen.go
  policybot/dashboard/topics/flakes/assets.gen.go
  policybot/dashboard/topics/home/assets.gen.go
  policybot/dashboard/topics/issues/assets.gen.go
  policybot/dashboard/topics/maintainers/assets.gen.go
  policybot/dashboard/topics/members/assets.gen.go
  policybot/dashboard/topics/perf/assets.gen.go
  policybot/dashboard/topics/pullrequests/assets.gen.go
  policybot/dashboard/topics/workinggroups/assets.gen.go
  policybot/handlers/githubwebhook/refresher/refresher.go
  policybot/mgrs/syncmgr/mgr.go
  policybot/pkg/blobstorage/gcs/store.go
  policybot/pkg/blobstorage/store.go
  policybot/pkg/pipeline/contracts.go
  policybot/pkg/pipeline/pipeline.go
  policybot/pkg/pipeline/pipeline_test.go
  policybot/pkg/pipeline/producer.go
  policybot/pkg/pipeline/producer_test.go
  policybot/pkg/pipeline/transformer.go
  policybot/pkg/resultgatherer/resultgatherer.go
  policybot/pkg/resultgatherer/resultgatherer_test.go
  policybot/pkg/storage/spanner/query.go
  policybot/pkg/storage/store.go
  policybot/pkg/storage/types.go
  policybot/pkg/testflakes/testflakes.go
  policybot/pkg/testflakes/testflakes_test.go
Labels: cla: yes, size/XXL

#114 Configure `istio/bots` for autodeployment from CI
  policybot/Makefile
Labels: cla: yes, size/S

#115 fix typescript config
  policybot/tsconfig.json
Labels: cla: yes, size/XS

#117 Add missing logic to the welcomer handler.
  policybot/handlers/githubwebhook/welcomer/welcomer.go
Labels: cla: yes, size/XS

#118 Update cron-syncmgr-testresults.yaml
  policybot/deploy/policybot/templates/cron-syncmgr-testresults.yaml
Labels: cla: yes, size/XS

#121 Update common files
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/license-lint.yml
  policybot/pkg/pipeline/producer_test.go
Labels: cla: yes, size/M
