Repository istio/bots, pull requests merged in 2019-11, with the labels that each got.

#97 PolicyBot improvements
  policybot/cmd/server.go
  policybot/handlers/githubwebhook/cfgmonitor/monitor.go
  policybot/handlers/githubwebhook/cleaner/cleaner.go
  policybot/handlers/githubwebhook/filters/filter.go
  policybot/handlers/githubwebhook/handler.go
  policybot/handlers/githubwebhook/labeler/labeler.go
  policybot/handlers/githubwebhook/lifecycler/lifecycler.go
  policybot/handlers/githubwebhook/nagger/nagger.go
  policybot/handlers/githubwebhook/refresher/refresher.go
  policybot/handlers/githubwebhook/testresultfilter/testresultfilter.go
  policybot/mgrs/lifecyclemgr/mgr.go
  policybot/policybot.yaml
Labels: cla: yes, size/L

#98 PolicyBot improvements
  policybot/cmd/lifecyclemgr.go
  policybot/cmd/server.go
  policybot/handlers/githubwebhook/lifecycler/lifecycler.go
  policybot/mgrs/lifecyclemgr/mgr.go
  policybot/pkg/storage/spanner/get.go
  policybot/policybot.yaml
Labels: cla: yes, size/L

#99 Fix bug causing the bot to update comments when it shouldn't.
  policybot/mgrs/lifecyclemgr/mgr.go
  policybot/pkg/gh/comments.go
Labels: cla: yes, size/XS

#100 don't set coverage status without a repo config
  policybot/Dockerfile
  policybot/handlers/githubwebhook/testresultfilter/testresultfilter.go
Labels: cla: yes, size/S

#103 Fix incorrect closing date shown in staleness comments.
  policybot/mgrs/lifecyclemgr/mgr.go
Labels: cla: yes, size/XS

#104 Fix dates in comments when an issue or PR has received no activity from an org member.
  policybot/mgrs/lifecyclemgr/mgr.go
Labels: cla: yes, size/S

#105 Synchronously query ZenHub for priority info as part of lifecycle management
  policybot/cmd/server.go
  policybot/handlers/githubwebhook/lifecycler/lifecycler.go
  policybot/pkg/storage/cache/cache.go
Labels: cla: yes, size/M

#106 PolicyBot improvements
  policybot/deploy/policybot/templates/cron-flakemgr.yaml
  policybot/deploy/policybot/templates/cron-labelmgr.yaml
  policybot/deploy/policybot/templates/cron-lifecyclemgr.yaml
  policybot/deploy/policybot/templates/cron-milestonemgr.yaml
  policybot/deploy/policybot/templates/cron-syncmgr-zenhub.yaml
  policybot/deploy/policybot/templates/cron-userdatamgr.yaml
  policybot/mgrs/syncmgr/fetch.go
  policybot/mgrs/syncmgr/mgr.go
  policybot/userdata.yaml
Labels: cla: yes, size/L

#108 Couple bug fixes.
  policybot/pkg/config/registry.go
  policybot/pkg/gh/repodesc.go
Labels: cla: yes, size/M
