Repository istio/bots, pull requests merged in 2020-10, with the labels that each got.

#283 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#284 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#281 update release qual test page
  policybot/dashboard/topics/releasequalification/assets.gen.go
  policybot/dashboard/topics/releasequalification/page.html
  policybot/dashboard/topics/releasequalification/topic.go
  policybot/pkg/storage/spanner/query.go
  policybot/pkg/storage/store.go
  policybot/pkg/storage/types.go
  policybot/spanner.ddl
Labels: cla: yes, size/L

#262 Track aborted tests in spanner
  go.mod
  go.sum
  licenses/cloud.google.com/go/bigquery/LICENSE
  licenses/cloud.google.com/go/spanner/LICENSE
  licenses/cloud.google.com/go/storage/LICENSE
  licenses/github.com/go-logr/logr/LICENSE
  licenses/github.com/gogo/protobuf/LICENSE
  licenses/github.com/golang/groupcache/LICENSE
  licenses/github.com/google/gofuzz/LICENSE
  licenses/github.com/hashicorp/golang-lru/LICENSE
  licenses/github.com/json-iterator/go/LICENSE
  licenses/github.com/modern-go/concurrent/LICENSE
  licenses/github.com/modern-go/reflect2/LICENSE
  licenses/golang.org/x/tools/third_party/moduleloader/LICENSE
  licenses/golang.org/x/tools/third_party/typescript/LICENSE
  licenses/google.golang.org/api/googleapi/internal/uritemplates/LICENSE
  licenses/google.golang.org/api/internal/third_party/uritemplates/LICENSE
  licenses/google.golang.org/protobuf/LICENSE
  licenses/gopkg.in/inf.v0/LICENSE
  licenses/k8s.io/api/LICENSE
  licenses/k8s.io/apimachinery/LICENSE
  licenses/k8s.io/klog/v2/LICENSE
  licenses/sigs.k8s.io/structured-merge-diff/v4/LICENSE
  policybot/pkg/resultgatherer/resultgatherer.go
  policybot/pkg/resultgatherer/resultgatherer_test.go
  policybot/pkg/resultgatherer/types.go
Labels: cla: yes, size/XXL

#286 Create 1.9 milestone
  policybot/config/milestones/1.9.yaml
Labels: cla: yes, size/XS

#265 Fix spanner performance bottleneck, re-enable flake detection
  policybot/dashboard/topics/postsubmit/topic.go
  policybot/dashboard/topics/releasequalification/assets.gen.go
  policybot/handlers/githubwebhook/refresher/refresher.go
  policybot/pkg/storage/spanner/query.go
  policybot/pkg/storage/spanner/schema.go
  policybot/pkg/storage/spanner/update.go
  policybot/pkg/storage/types.go
Labels: cla: yes, size/L

#288 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#287 fix edge conditions
  policybot/pkg/resultgatherer/resultgatherer.go
Labels: cla: yes, size/XS

#289 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#290 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#291 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#292 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#293 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#294 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#295 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#296 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
