Repository istio/bots, pull requests merged in 2020-09, with the labels that each got.

#263 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#264 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#266 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#267 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#268 Remove Zenhub from policy bot
  policybot/Makefile
  policybot/README.md
  policybot/cmd/server.go
  policybot/cmd/syncmgr.go
  policybot/dashboard/dashboard.go
  policybot/dashboard/topics/coverage/topic.go
  policybot/dashboard/topics/features/topic.go
  policybot/dashboard/topics/flakes/topic.go
  policybot/dashboard/topics/maintainers/topic.go
  policybot/dashboard/topics/members/topic.go
  policybot/dashboard/topics/perf/topic.go
  policybot/dashboard/topics/postsubmit/assets.gen.go
  policybot/dashboard/topics/pullrequests/topic.go
  policybot/dashboard/topics/webanalytics/assets.gen.go
  policybot/dashboard/topics/webanalytics/topic.go
  policybot/deploy/policybot/templates/cron-syncmgr-zenhub.yaml
  policybot/deploy/policybot/templates/secret.yaml
  policybot/deploy/policybot/values.yaml
  policybot/handlers/githubwebhook/cleaner/cleaner.go
  policybot/handlers/githubwebhook/labeler/labeler.go
  policybot/handlers/githubwebhook/lifecycler/lifecycler.go
  policybot/handlers/githubwebhook/welcomer/welcomer.go
  policybot/handlers/zenhubwebhook/handler.go
  policybot/mgrs/lifecyclemgr/mgr.go
  policybot/mgrs/syncmgr/mgr.go
  policybot/mgrs/syncmgr/mgr_test.go
  policybot/mgrs/userdatamgr/mgr.go
  policybot/pkg/blobstorage/gcs/store.go
  policybot/pkg/cmdutil/secrets.go
  policybot/pkg/cmdutil/util.go
  policybot/pkg/resultgatherer/resultgatherer.go
  policybot/pkg/resultgatherer/resultgatherer_test.go
  policybot/pkg/storage/cache/cache.go
  policybot/pkg/storage/spanner/read.go
  policybot/pkg/storage/spanner/schema.go
  policybot/pkg/storage/spanner/store.go
  policybot/pkg/storage/spanner/update.go
  policybot/pkg/storage/spanner/write.go
  policybot/pkg/storage/store.go
  policybot/pkg/storage/types.go
  policybot/pkg/zh/client.go
  policybot/pkg/zh/issueData.go
  policybot/pkg/zh/throttled.go
Labels: cla: yes, size/XL

#270 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#271 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/M

#272 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#273 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#274 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#275 Make format part of gen
  Makefile.core.mk
Labels: cla: yes, size/XS

#276 Set SHELL to bash
  Makefile.core.mk
Labels: cla: yes, size/XS

#277 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#278 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#261 add entry for release qualification pipeline
  policybot/dashboard/dashboard.go
  policybot/dashboard/topics/releasequalification/assets.gen.go
  policybot/dashboard/topics/releasequalification/page.html
  policybot/dashboard/topics/releasequalification/topic.go
  policybot/pkg/storage/spanner/query.go
  policybot/pkg/storage/spanner/read.go
  policybot/pkg/storage/spanner/schema.go
  policybot/pkg/storage/store.go
  policybot/pkg/storage/types.go
  policybot/spanner.ddl
Labels: cla: yes, size/L

#280 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.yamllint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/S

#282 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/.yamllint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS
