Repository istio/bots, pull requests merged in 2020-05, with the labels that each got.

#180 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#181 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#182 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#183 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#184 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#185 guard GetTestResults from malformed files
  policybot/pkg/resultgatherer/resultgatherer.go
Labels: cla: yes, size/XS

#186 push bots image to ubuntu:19.10 since 19.04 is no longer supported
  policybot/Dockerfile
Labels: cla: yes, size/XS

#187 Improve resultgatherer error messages for logs
  policybot/pkg/resultgatherer/resultgatherer.go
Labels: cla: yes, size/S

#188 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#189 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#190 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#191 Add product security label
  policybot/config/autolabels/product-security.yaml
  policybot/config/boilerplates/area-selection.yaml
Labels: cla: yes, size/XS

#192 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#193 ignore '429 too many requests' responses during link checking.
  common/Makefile.common.mk
Labels: cla: yes, size/XS
