Repository istio/bots, pull requests merged in 2020-08, with the labels that each got.

#245 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#246 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#248 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#250 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#251 Temporarily disable flake detection
  policybot/mgrs/syncmgr/mgr.go
Labels: cla: yes, size/XS

#252 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#253 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci-format.yml
  common/scripts/format_go.sh
Labels: auto-merge, cla: yes, release-notes-none, size/M

#247 put css in sass
  policybot/dashboard/sass/_all.scss
  policybot/dashboard/sass/misc/_analysis.scss
  policybot/dashboard/topics/postsubmit/analysis.html
  policybot/dashboard/topics/postsubmit/assets.gen.go
Labels: cla: yes, size/L

#255 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#257 Fix vet warning for string(x)
  policybot/handlers/githubwebhook/refresher/refresher.go
Labels: cla: yes, size/XS

#256 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#258 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#259 disable all activity on TestResults table to mitigate outage
  policybot/dashboard/topics/postsubmit/topic.go
  policybot/handlers/githubwebhook/refresher/refresher.go
Labels: cla: yes, size/M

#260 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
