Repository istio/bots, pull requests merged in 2020-11, with the labels that each got.

#297 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#298 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#299 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#300 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#301 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#302 Add 'Upgrade' to the autolabeler config
  policybot/config/autolabels/upgrade.yaml
Labels: cla: yes, size/XS

#304 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#303 ignore the monitors if the test is stale
  policybot/dashboard/topics/releasequalification/topic.go
Labels: cla: yes, size/M

#305 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#306 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#308 Close 1.6 milestone
  policybot/config/milestones/1.6.yaml
Labels: cla: yes, size/XS

#309 remove old cherrypick labels
  policybot/config/labels/cherrypick-release-1.5.yaml
  policybot/config/labels/cherrypick-release-1.6.yaml
Labels: cla: yes, size/XS

#310 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#307 Close 1.5 milestone
  policybot/config/milestones/1.5.yaml
Labels: cla: yes, size/XS
