Repository istio/bots, pull requests merged in 2020-03, with the labels that each got.

#141 Nagger should rescan PR on updates
  policybot/handlers/githubwebhook/nagger/nagger.go
Labels: cla: yes, size/XS

#142 Automator: update common-files@master in istio/bots@master
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#143 Automator: update common-files@master in istio/bots@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#144 Add 1.7 milestone
  policybot/config/milestones/1.7.yaml
Labels: cla: yes, size/XS

#145 Nagger should refresh data on updates
  policybot/handlers/githubwebhook/refresher/refresher.go
Labels: cla: yes, size/XS

#146 Automator: update common-files@master in istio/bots@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#147 Automator: update common-files@master in istio/bots@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#148 Automator: update common-files@master in istio/bots@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#149 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#151 ignore out/ dir
  .gitignore
Labels: cla: yes, size/XS

#150 Automator: update common-files@master in istio/bots@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#152 Automator: update common-files@master in istio/bots@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#153 Automator: update common-files@master in istio/bots@master
  Makefile
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#154 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#155 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#156 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#157 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#158 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#159 Added types and backlog milestone
  policybot/config/autolabels/multi-control-plane.yaml
  policybot/config/autolabels/multicluster.yaml
  policybot/config/autolabels/virtualmachine.yaml
  policybot/config/milestones/backlog.yaml
Labels: cla: yes, size/S

#160 Automator: update common-files@master in istio/bots@master
  Makefile
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#161 This renames `type` to `feature` and adds boilerplate cleanup for feature
  policybot/config/autolabels/multi-cluster.yaml
  policybot/config/autolabels/multi-control-plane.yaml
  policybot/config/autolabels/virtual-machine.yaml
  policybot/config/boilerplates/feature-selection-banner.yaml
  policybot/config/boilerplates/feature-selection.yaml
Labels: cla: yes, size/S

#162 Fixed regex to match autolabels
  policybot/config/boilerplates/area-selection.yaml
  policybot/config/boilerplates/feature-selection.yaml
Labels: cla: yes, size/S
