Repository istio/bots, pull requests merged in 2020-01, with the labels that each got.

#122 Update test nag to not fire for updated testdata
  policybot/config/nags/go.yaml
Labels: cla: yes, size/XS

#116 Enable welcomer bot for istio/test-infra
  policybot/config/welcome/test-infra.yaml
Labels: cla: yes, size/S

#123 Add cache update to test results bot job
  policybot/mgrs/syncmgr/mgr.go
  policybot/pkg/storage/spanner/update.go
  policybot/pkg/storage/store.go
Labels: cla: yes, size/M

#124 Prevent pipelines from passing nil errors on To()
  policybot/pkg/pipeline/pipeline.go
  policybot/pkg/pipeline/pipeline_test.go
Labels: cla: yes, size/M

#125 Add flake dashboard to eng.istio.io
  policybot/dashboard/topics/flakes/page.html
Labels: cla: yes, size/XS

#126 Include reopening issues as a form of member comment activity
  policybot/pkg/storage/spanner/get.go
Labels: cla: yes, size/S

#127 Add cherrypick-release-1.5 label
  policybot/config/labels/cherrypick-release-1.5.yaml
Labels: cla: yes, size/XS
