Repository istio/bots, pull requests merged in 2020-02, with the labels that each got.

#129 Automator: update common-files@master in istio/bots@master
  LICENSE
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/lint_go.sh
Labels: cla: yes, size/M

#128 Enable cert auto-rotation for eng.istio.io
  policybot/deploy/policybot/templates/certificate.yaml
  policybot/deploy/policybot/templates/ingress.yaml
Labels: cla: yes, size/S

#130 Automator: update common-files@master in istio/bots@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#131 Automator: update common-files@master in istio/bots@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#132 Add auto-merge label
  policybot/config/labels/auto-merge.yaml
Labels: cla: yes, size/XS

#133 Automator: update common-files@master in istio/bots@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#134 Welcomer: exclude current PR from resend logic
  policybot/handlers/githubwebhook/welcomer/welcomer.go
Labels: cla: yes, size/XS

#135 Welcomer: enable welcomer all core istio repos
  policybot/config/welcome/default.yaml
Labels: cla: yes, size/S

#136 Welcomer: generalize welcome message
  policybot/config/welcome/default.yaml
Labels: cla: yes, size/XS

#137 Template and personalize bot message
  policybot/config/welcome/default.yaml
  policybot/handlers/githubwebhook/nagger/nagger.go
  policybot/handlers/githubwebhook/welcomer/welcomer.go
  policybot/mgrs/flakemgr/mgr.go
  policybot/mgrs/lifecyclemgr/mgr.go
  policybot/pkg/coverage/coverage.go
  policybot/pkg/gh/comments.go
Labels: cla: yes, size/M

#138 Automator: update common-files@master in istio/bots@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#139 Automator: update common-files@master in istio/bots@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#140 Welcomer: minor message format tweaks
  policybot/config/welcome/default.yaml
Labels: cla: yes, size/XS
