Repository istio/bots, pull requests merged in 2020-12, with the labels that each got.

#311 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#312 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#314 Unblock Flake Detection
  policybot/mgrs/syncmgr/mgr.go
  policybot/pkg/resultgatherer/resultgatherer.go
  policybot/pkg/storage/spanner/query.go
  policybot/pkg/storage/spanner/update.go
  policybot/pkg/storage/types.go
Labels: cla: yes, size/M

#315 Move to Ubuntu lts
  policybot/Dockerfile
Labels: cla: yes, size/XS

#316 remove pin for ca-certificates in policybot
  policybot/Dockerfile
Labels: cla: yes, size/XS
