Repository istio/bots, pull requests merged in 2020-06, with the labels that each got.

#194 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#195 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/XS

#196 add PostSubmitTestResults table
  policybot/spanner.ddl
Labels: cla: yes, ok-to-test, size/S

#198 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#199 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#200 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: auto-merge, cla: yes, size/XS

#201 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/M

#197 Add post submit function, delete pullrequest
  policybot/mgrs/syncmgr/mgr.go
  policybot/pkg/resultgatherer/resultgatherer.go
  policybot/pkg/resultgatherer/resultgatherer_test.go
  policybot/pkg/storage/spanner/query.go
  policybot/pkg/storage/spanner/read.go
  policybot/pkg/storage/spanner/schema.go
  policybot/pkg/storage/spanner/write.go
  policybot/pkg/storage/store.go
  policybot/pkg/storage/types.go
Labels: cla: yes, ok-to-test, size/L

#203 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/copyright-banner-go.txt
  common/scripts/fix_copyright_banner.sh
Labels: auto-merge, cla: yes, size/M

#202 add artifact table
  policybot/pkg/storage/spanner/schema.go
  policybot/pkg/storage/spanner/write.go
  policybot/pkg/storage/store.go
  policybot/pkg/storage/types.go
  policybot/spanner.ddl
Labels: cla: yes, ok-to-test, size/L

#205 Fix Interleave table names
  policybot/spanner.ddl
Labels: cla: yes, size/XS

#204 Read yaml files while gathering post submit result and write to ddl
  policybot/mgrs/syncmgr/mgr.go
  policybot/pkg/resultgatherer/resultgatherer.go
  policybot/pkg/resultgatherer/resultgatherer_test.go
  policybot/pkg/storage/types.go
Labels: cla: yes, size/L

#206 Added needs documnetation label
  policybot/config/labels/needs-documentation.yaml
Labels: cla: yes, size/XS

#208 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#209 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#210 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#207 create batch for testoutcome and featureLabel
  policybot/mgrs/syncmgr/mgr.go
  policybot/pkg/storage/types.go
Labels: cla: yes, size/M

#211 change batch size
  policybot/mgrs/syncmgr/mgr.go
Labels: cla: yes, size/XS

#212 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/fix_copyright_banner.sh
Labels: auto-merge, cla: yes, size/XS

#213 further split batch size
  policybot/mgrs/syncmgr/mgr.go
Labels: cla: yes, size/M

#214 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, size/XS

#215 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS
