Repository istio/bots, pull requests merged in 2020-07, with the labels that each got.

#216 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#217 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#218 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#219 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/S

#220 Create 1.8.yaml
  policybot/config/milestones/1.8.yaml
Labels: cla: yes, size/XS

#221 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#222 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#223 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#224 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#225 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#226 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/S

#227 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#228 Add release-notes-none label
  policybot/config/labels/release-notes-none.yaml
Labels: cla: yes, size/XS

#229 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#232 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#231 add post submit test result analysis page
  go.mod
  go.sum
  licenses/github.com/robfig/cron/v3/LICENSE
  policybot/dashboard/dashboard.go
  policybot/dashboard/sass/_all.scss
  policybot/dashboard/topics/flakes/assets.gen.go
  policybot/dashboard/topics/postsubmit/analysis.html
  policybot/dashboard/topics/postsubmit/assets.gen.go
  policybot/dashboard/topics/postsubmit/chooseBaseSha.html
  policybot/dashboard/topics/postsubmit/page.html
  policybot/dashboard/topics/postsubmit/topic.go
  policybot/pkg/storage/cache/cache.go
  policybot/pkg/storage/spanner/query.go
  policybot/pkg/storage/spanner/store.go
  policybot/pkg/storage/store.go
  policybot/pkg/storage/types.go
Labels: cla: yes, size/XL

#234 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, size/XS

#235 Create cherrypick-release-1.7.yaml
  policybot/config/labels/cherrypick-release-1.7.yaml
Labels: cla: yes, size/XS

#233 Add istio.io website dashboard to eng.istio.io
  policybot/dashboard/dashboard.go
  policybot/dashboard/topics/webanalytics/assets.gen.go
  policybot/dashboard/topics/webanalytics/page.html
  policybot/dashboard/topics/webanalytics/topic.go
Labels: cla: yes, size/M

#237 Add cherrypick label for 1.8
  policybot/config/labels/cherrypick-release-1.8.yaml
Labels: cla: yes, size/XS

#238 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/XS

#239 Release-notes-none autolable
  policybot/config/autolabels/release-notes.yaml
Labels: cla: yes, size/XS

#240 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#236 Add feature coverage dashboard with test details
  policybot/dashboard/dashboard.go
  policybot/dashboard/topics/postsubmit/analysis.html
  policybot/dashboard/topics/postsubmit/assets.gen.go
  policybot/dashboard/topics/postsubmit/page.html
  policybot/dashboard/topics/postsubmit/topic.go
  policybot/pkg/storage/spanner/query.go
  policybot/pkg/storage/spanner/store.go
  policybot/pkg/storage/store.go
  policybot/pkg/storage/types.go
Labels: cla: yes, size/L

#241 Add basesha info to the feature coverage dashboard analysis page
  policybot/dashboard/topics/postsubmit/analysis.html
  policybot/dashboard/topics/postsubmit/assets.gen.go
  policybot/dashboard/topics/postsubmit/topic.go
  policybot/pkg/storage/cache/cache.go
  policybot/pkg/storage/spanner/query.go
  policybot/pkg/storage/store.go
Labels: cla: yes, size/M

#242 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#244 Remove old labels
  policybot/config/autolabels/config.yaml
  policybot/config/autolabels/policies-and-telemetry.yaml
  policybot/config/labels/cherrypick-release-1.2.yaml
  policybot/config/labels/cherrypick-release-1.3.yaml
  policybot/config/labels/cherrypick-release-1.4.yaml
  policybot/config/labels/flag-needs-backport.yaml
  policybot/config/labels/needs-rebase.yaml
Labels: cla: yes, size/S
