Repository istio/bots, pull requests merged in 2021-08, with the labels that each got.

#394 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#395 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#397 Create a label for issues on the Release 1.12 Roadmap
  policybot/config/labels/roadmap-1.12.yaml
Labels: size/XS, cla: yes

#398 Update roadmap label
  policybot/config/labels/roadmap-1.12.yaml
Labels: size/XS, cla: yes

#396 1.9 EOL
  policybot/config/labels/cherrypick-release-1.9.yaml
  policybot/config/milestones/1.9.yaml
Labels: size/XS, cla: yes

#399 Add tests for clean regex matches
  go.mod
  policybot/config/boilerplates/area-selection.yaml
  policybot/config/boilerplates/note-about-bugs.yaml
  policybot/handlers/githubwebhook/cleaner/cleaner_test.go
  policybot/handlers/githubwebhook/cleaner/testdata/issue-default.out.txt
  policybot/handlers/githubwebhook/cleaner/testdata/issue-default.txt
Labels: size/L, cla: yes

#401 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
Labels: size/XS, cla: yes, auto-merge, release-notes-none
