Repository istio/bots, pull requests merged in 2021-05, with the labels that each got.

#360 Fix release note label
  policybot/config/autolabels/release-notes.yaml
Labels: cla: yes, size/XS

#361 Automator: update common-files@master in istio/bots@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#363 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#364 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#365 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#366 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#367 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#368 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#369 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#370 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#371 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
