Repository istio/bots, pull requests merged in 2021-04, with the labels that each got.

#349 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#350 Add release-1.10 cherrypick label and 1.11 milestone
  policybot/config/labels/cherrypick-release-1.10.yaml
  policybot/config/milestones/1.11.yaml
Labels: cla: yes, size/XS

#351 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#352 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#353 Update common files to master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#355 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#356 Add product security label
  policybot/config/labels/product-security.yaml
Labels: cla: yes, size/XS

#357 update the projectId to be spanner nullstring
  policybot/pkg/storage/types.go
  policybot/spanner.ddl
Labels: cla: yes, size/XS

#358 set more optional fields as nullable
  policybot/dashboard/topics/releasequalification/topic.go
  policybot/pkg/storage/types.go
Labels: cla: yes, size/S

#359 Release-notes-none autolabel
  policybot/config/autolabels/release-notes.yaml
Labels: cla: yes, size/XS
