Repository istio/bots, pull requests merged in 2021-11, with the labels that each got.

#413 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#414 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#415 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#416 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#417 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#418 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, cla: yes, auto-merge, release-notes-none

#419 Automator: update common-files@master in istio/bots@master
  Makefile
  common/.commonfiles.sha
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#420 Update yaml library to use sigs.k8s.io/yaml
  go.mod
  licenses/sigs.k8s.io/yaml/LICENSE
  policybot/handlers/githubwebhook/cleaner/cleaner_test.go
  policybot/mgrs/syncmgr/mgr.go
  policybot/pkg/config/registry.go
  policybot/pkg/coverage/config.go
  policybot/pkg/resultgatherer/resultgatherer.go
Labels: size/M, cla: yes

#421 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, cla: yes, auto-merge, release-notes-none

#422 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none

#423 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, cla: yes, auto-merge, release-notes-none
