Repository istio/bots, pull requests merged in 2022-08, with the labels that each got.

#532 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#534 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#535 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#536 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#537 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#539 Run `make gen` with Go 1.19 to format files
  policybot/handlers/githubwebhook/nagger/record.go
Labels: size/XS

#538 Create cherrypick-release-1.15.yaml
  policybot/config/labels/cherrypick-release-1.15.yaml
Labels: size/XS

#540 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#541 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#542 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
Labels: size/XS, auto-merge, release-notes-none

#543 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#544 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#545 Cleanup of labels/milestones
  go.mod
  policybot/config/labels/cherrypick-release-1.10.yaml
  policybot/config/labels/cherrypick-release-1.11.yaml
  policybot/config/labels/cherrypick-release-1.12.yaml
  policybot/config/labels/roadmap-1.12.yaml
  policybot/config/milestones/1.10.yaml
  policybot/config/milestones/1.11.yaml
  policybot/config/milestones/1.12.yaml
  policybot/handlers/githubwebhook/cleaner/cleaner_test.go
  policybot/mgrs/syncmgr/mgr.go
  policybot/pkg/config/registry.go
  policybot/pkg/coverage/config.go
  policybot/pkg/coverage/coverage.go
  policybot/pkg/resultgatherer/resultgatherer.go
Labels: size/L
