Repository istio/bots, pull requests merged in 2022-04, with the labels that each got.

#478 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#479 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#480 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#481 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#482 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#484 Update common-files (with new linter) and lint fixes
  common/.commonfiles.sha
  common/config/.golangci.yml
  policybot/pkg/resultgatherer/types.go
Labels: size/M

#486 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#487 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#488 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#489 add cherry pick label for 1.14
  policybot/config/labels/cherrypick-release-1.14.yaml
Labels: size/XS

#490 groovy is EOL, replace with jammy
  policybot/Dockerfile
Labels: size/XS

#492 add release 1.15 milestone tracker
  policybot/config/milestones/1.15.yaml
Labels: size/XS

#493 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#494 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, auto-merge, release-notes-none

#495 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#496 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/S, auto-merge, release-notes-none
