Repository istio/bots, pull requests merged in 2022-01, with the labels that each got.

#431 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#432 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#433 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#434 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#435 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#436 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#437 Create a cherry-pick-1.13 label
  policybot/config/labels/cherrypick-release-1.13.yaml
  policybot/config/milestones/1.14.yaml
Labels: size/XS

#438 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#439 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#440 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#442 Fix linting failures before updating to new build-tools image
  policybot/dashboard/templates/layout/assets.gen.go
  policybot/dashboard/templates/widgets/assets.gen.go
  policybot/dashboard/topics/commithub/assets.gen.go
  policybot/dashboard/topics/coverage/assets.gen.go
  policybot/dashboard/topics/features/assets.gen.go
  policybot/dashboard/topics/flakes/assets.gen.go
  policybot/dashboard/topics/home/assets.gen.go
  policybot/dashboard/topics/issues/assets.gen.go
  policybot/dashboard/topics/maintainers/assets.gen.go
  policybot/dashboard/topics/members/assets.gen.go
  policybot/dashboard/topics/perf/assets.gen.go
  policybot/dashboard/topics/postsubmit/assets.gen.go
  policybot/dashboard/topics/pullrequests/assets.gen.go
  policybot/dashboard/topics/releasequalification/assets.gen.go
  policybot/dashboard/topics/webanalytics/assets.gen.go
  policybot/dashboard/topics/workinggroups/assets.gen.go
  policybot/deploy/policybot/templates/cron-flakemgr.yaml
  policybot/deploy/policybot/templates/cron-labelmgr.yaml
  policybot/deploy/policybot/templates/cron-lifecyclemgr.yaml
  policybot/deploy/policybot/templates/cron-milestonemgr.yaml
  policybot/deploy/policybot/templates/cron-syncmgr-events.yaml
  policybot/deploy/policybot/templates/cron-syncmgr-issues.yaml
  policybot/deploy/policybot/templates/cron-syncmgr-misc.yaml
  policybot/deploy/policybot/templates/cron-syncmgr-prs.yaml
  policybot/deploy/policybot/templates/cron-syncmgr-testresults.yaml
  policybot/deploy/policybot/templates/cron-syncmgr-users.yaml
  policybot/deploy/policybot/templates/cron-userdatamgr.yaml
  policybot/deploy/policybot/templates/ingress.yaml
  policybot/pkg/blobstorage/store.go
  policybot/pkg/cmdutil/util.go
  policybot/pkg/pipeline/contracts.go
  policybot/pkg/resultgatherer/resultgatherer.go
  policybot/pkg/storage/store.go
Labels: size/M

#441 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/lint_go.sh
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#443 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#444 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#445 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
