Repository istio/bots, pull requests merged in 2023-03, with the labels that each got.

#636 Add dual stack label to support experimental support triaging
  policybot/config/autolabels/dualstack.yaml
  policybot/config/boilerplates/area-selection.yaml
  policybot/handlers/githubwebhook/cleaner/testdata/issue-default.txt
Labels: size/S

#649 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#650 Automator: update common-files@master in istio/bots@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#651 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#652 Fix up some dependabot alerts
  go.mod
  go.sum
Labels: size/S

#653 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#654 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#655 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#656 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/M, auto-merge, release-notes-none

#657 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#658 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
Labels: size/L, auto-merge, release-notes-none
