Repository istio/bots, pull requests merged in 2023-06, with the labels that each got.

#679 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#680 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#681 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#682 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#684 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#686 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#687 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#688 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#690 Fix panic in job gatherer
  policybot/pkg/resultgatherer/resultgatherer.go
Labels: size/XS, release-notes-none

#691 helm: drop secrets
  policybot/Makefile
  policybot/deploy/policybot/templates/secret.yaml
  policybot/deploy/policybot/values.yaml
Labels: size/S, release-notes-none

#692 Move from exported SA key to workload identity
  policybot/README.md
  policybot/cmd/flakemgr.go
  policybot/cmd/lifecyclemgr.go
  policybot/cmd/server.go
  policybot/cmd/syncmgr.go
  policybot/cmd/userdatamgr.go
  policybot/deploy/policybot/templates/deployment-server.yaml
  policybot/deploy/policybot/templates/service-account.yaml
  policybot/deploy/policybot/values.yaml
  policybot/pkg/blobstorage/gcs/store.go
  policybot/pkg/cmdutil/secrets.go
  policybot/pkg/cmdutil/util.go
  policybot/pkg/resultgatherer/resultgatherer_test.go
  policybot/pkg/storage/spanner/store.go
Labels: size/M, release-notes-none

#694 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#695 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#696 Use do-not-merge/hold instead of do-not-merge
  policybot/config/labels/do-not-merge-hold.yaml
Labels: size/XS

#697 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#699 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
