Repository istio/bots, pull requests merged in 2023-07, with the labels that each got.

#700 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#701 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#702 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#703 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#704 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#706 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#707 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#708 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#709 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#710 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#711 Fix cronjobs missing service account and archived repos
  policybot/config/core.yaml
  policybot/config/welcome/default.yaml
  policybot/deploy/policybot/templates/cron-labelmgr.yaml
  policybot/deploy/policybot/templates/cron-lifecyclemgr.yaml
  policybot/deploy/policybot/templates/cron-milestonemgr.yaml
  policybot/deploy/policybot/templates/cron-syncmgr-events.yaml
  policybot/deploy/policybot/templates/cron-syncmgr-issues.yaml
  policybot/deploy/policybot/templates/cron-syncmgr-misc.yaml
  policybot/deploy/policybot/templates/cron-syncmgr-prs.yaml
  policybot/deploy/policybot/templates/cron-syncmgr-testresults.yaml
  policybot/deploy/policybot/templates/cron-syncmgr-users.yaml
  policybot/deploy/policybot/templates/cron-userdatamgr.yaml
Labels: size/S, release-notes-none

#712 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/tracing.sh
Labels: size/L, auto-merge, release-notes-none

#713 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/tracing.sh
Labels: size/S, auto-merge, release-notes-none

#714 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
