Repository istio/bots, pull requests merged in 2023-09, with the labels that each got.

#730 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#731 Add 1.20 milestone and close older milestones
  policybot/config/milestones/1.15.yaml
  policybot/config/milestones/1.16.yaml
  policybot/config/milestones/1.17.yaml
  policybot/config/milestones/1.20.yaml
Labels: size/S

#732 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#733 Bot text changes
  policybot/config/welcome/default.yaml
  policybot/config/welcome/istio.io.yaml
Labels: size/M

#734 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#735 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#736 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/S, auto-merge, release-notes-none
