Repository istio/bots, pull requests merged in 2023-10, with the labels that each got.

#737 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/S, auto-merge, release-notes-none

#738 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#739 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#740 Create 1.20 cherry-pick label
  .gitignore
  policybot/config/labels/cherrypick-release-1.20.yaml
Labels: size/XS

#741 Add 1.21 milestone
  policybot/config/milestones/1.21.yaml
Labels: size/XS

#742 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#743 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#744 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#745 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#747 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#748 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#749 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#750 Automator: update common-files@master in istio/bots@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#754 Automator: update common-files@master in istio/bots@master
  LICENSE
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none
