Repository istio/bots, pull requests merged in 2023-02, with the labels that each got.

#625 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#626 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#627 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#628 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#629 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#630 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#631 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#634 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#635 Bump github.com/prometheus/client_golang from 0.9.3 to 1.11.1
  go.mod
  go.sum
  licenses/github.com/cespare/xxhash/v2/LICENSE.txt
  licenses/github.com/prometheus/client_model/ruby/LICENSE
Labels: size/L

#637 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#638 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#640 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#641 Add 1.18 milestone and push items to new repos.
  policybot/config/core.yaml
  policybot/config/milestones/1.18.yaml
  policybot/config/welcome/default.yaml
Labels: size/XS

#642 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#645 Automator: update common-files@master in istio/bots@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#647 Further changes for v1
  policybot/deploy/policybot/templates/ingress.yaml
Labels: size/XS

#648 Add kubectl config view
  policybot/Makefile
Labels: size/XS
